<center><h1>Tensors</h1></center>

A tensor is a multi-linear algebraic object that relates sets of algebraic objects related to a vector space (like vectors and scalars). It can be represented by a multi-dimensional array of numerical components.

Or you can think of them like, a tensor is a way to organize and represent data that can have multiple "directions" or "indices." The number of these "directions" is called the order or rank of the tensor.

Think of it like organizing information in boxes within boxes within boxes... each level of nesting adds another dimension.

- Scalar: The simplest kind of data is just a single number, like your age (e.g., 30) or the temperature outside (e.g., 25 degrees Celsius). This is a 0-dimensional tensor or a scalar. It has no direction.

- Vector: Now imagine you're describing the wind. You need more than just a number. You need a direction and a strength (or magnitude). For example, "5 kilometers per hour to the East." This is a 1-dimensional tensor or a vector. It has one "direction" or axis. Think of it as an arrow in space.

- Matrix: Let's say you have a table of data, like the test scores of several students in different subjects. This table has rows (students) and columns (subjects). Each entry in the table is a number, but the arrangement gives it more meaning. This entire table is a 2-dimensional tensor or a matrix. It has two "directions" or axes (rows and columns).

- Higher-Dimensional Tensors (Beyond Matrices):Think of a multi channel image (Channel, x, y)

> Ex - Imagine you have multiple of those student-subject score tables, maybe one for each grade level in a school. Now you have a collection of matrices, and you can identify each matrix by the grade level. This whole structure (all the tables organized by grade) could be thought of as a 3-dimensional tensor. It has three "directions" or axes (students, subjects, grades).

> You can keep going! Imagine you have these grade-level score collections for multiple years. Now you have a 4-dimensional tensor (students, subjects, grades, years).

**The “dimension” of a tensor is the number of indices to specify
one of its coefficients.**

An element of $ \mathbb{R}^3$ is a three-dimension vector, but a one-dimension tensor.

In [1]:
import torch

In [4]:
x = torch.empty(2,5)
print(x)
print(x.size())

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


In [9]:
x = torch.tensor([10., 20., 30.])
y = torch.tensor([11., 22., 33.])
print("Size of each tensor: ", x.size(), "and ", y.size())

Size of each tensor:  torch.Size([3]) and  torch.Size([3])


In [10]:
x + y

tensor([21., 42., 63.])

- component-wise product and can be applied to tensors of arbitrary size, in particular of dimension greater than 2.

In [11]:
x * y

tensor([110., 440., 990.])

In [12]:
x**2

tensor([100., 400., 900.])

In [15]:
m = torch.tensor([[0., 0., 3.],
                  [0., 2., 0.],
                  [1., 0., 0.]])
m.size()                  

torch.Size([3, 3])

- Matrix - Vector multiplication

In [21]:
m.mv(x)

tensor([90., 40., 10.])

- The @ operator corresponds to matrix/vector
or matrix/matrix multiplication

In [22]:
m @ x

tensor([90., 40., 10.])

- Standard linear operation:

In [25]:
y = torch.randn(3)
y

tensor([ 0.0118, -1.4046,  0.0870])

In [26]:
m = torch.randn(3,3)
m

tensor([[-0.3422,  1.4005, -1.4339],
        [ 0.9116,  0.0536, -3.7168],
        [ 0.2989,  0.6960,  1.3959]])

In [29]:
q = torch.linalg.lstsq(m, y).solution
q

tensor([-0.7269,  0.0357,  0.2001])

- ```torch.linalg.lstsq(m, y).solution``` calculates the least-squares solution to a system of linear equations represented by $mx=y$. 

In [30]:
m @ q

tensor([ 0.0118, -1.4046,  0.0870])

In [32]:
x = torch.tensor([ [ 1, 3, 0 ],
                [ 2, 4, 6 ] ])
x

tensor([[1, 3, 0],
        [2, 4, 6]])

In [33]:
x.view(-1)

tensor([1, 3, 0, 2, 4, 6])

- Broadcasting

> When the shape of the objects on which we want to perform operation are reasonable, **Broadcasting** automatically expand dimensions by replicating coefficients form one of the two objects.

In [38]:
x = torch.empty(100, 4).normal_(2)
print(x.mean(0))


tensor([1.9598, 2.1009, 2.0909, 1.9276]) tensor([1.0110, 1.0674, 1.0586, 0.9748])


In [41]:
 x -= x.mean(0) 
x.mean(0)

tensor([-4.7684e-09, -4.7684e-09, -7.1526e-09,  4.7684e-09])

This shouldn't have worked because x.mean(0) was a tensor of size (1,4) and x is of (100,4), but it subtracted x.mean(0) from all the rows as if like it has been replicated 100 times for each row.

In [45]:
A = torch.tensor([[1.], [2.], [3.], [4.]])
A

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [46]:
B = torch.tensor([[5., -5., 5., -5., 5.]])
B

tensor([[ 5., -5.,  5., -5.,  5.]])

In [47]:
C = A + B
C

tensor([[ 6., -4.,  6., -4.,  6.],
        [ 7., -3.,  7., -3.,  7.],
        [ 8., -2.,  8., -2.,  8.],
        [ 9., -1.,  9., -1.,  9.]])

- Einstein Summation

> ```torch.einsum()``` function,  is a powerful and concise way to express a wide variety of multi-dimensional tensor operations. It's based on the Einstein summation convention, a mathematical notation that simplifies expressions involving sums of products of tensor elements.
>
> ``torch.einsum()`` takes as argument a string describing the operation, the tensors to
operate on, and returns a tensor.

In [49]:
p = torch.rand(2, 5)
p

tensor([[0.1349, 0.0879, 0.6697, 0.6804, 0.8671],
        [0.9849, 0.1816, 0.5192, 0.3852, 0.8469]])

In [50]:
q = torch.rand(5,4)
q

tensor([[0.2285, 0.9549, 0.2475, 0.4728],
        [0.0553, 0.1869, 0.3138, 0.0047],
        [0.0716, 0.4772, 0.8463, 0.4394],
        [0.4488, 0.9805, 0.2755, 0.6760],
        [0.6684, 0.0474, 0.5572, 0.2332]])

In [51]:
torch.einsum('ij,jk->ik', p, q)

tensor([[0.9686, 1.1731, 1.2984, 1.0206],
        [1.0112, 1.6400, 1.3183, 1.1525]])

In [52]:
p @ q

tensor([[0.9686, 1.1731, 1.2984, 1.0206],
        [1.0112, 1.6400, 1.3183, 1.1525]])